
	<?php
		// some helpers
		$_helper = $this->helper('catalog/output');
		$storeId = Mage::app()->getStore()->getId();
		$catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);

		// get all products that are marked as featured
		$collection = Mage::getModel('catalog/product')->getCollection();
		$collection->addAttributeToSelect('featured_product');
		$collection->addFieldToFilter(array(
			array('attribute' => 'featured_product', 'eq' => true),
		));

		// if no products are currently featured, display some text
		if (!$collection->count()) :
	?>

	<p class="note-msg"><?php echo $this->__('There are no featured products at the moment.') ?></p>

	<?php else : ?>

	<div class="category-products">

	<?php
		$_collectionSize = $collection->count();
		$_columnCount = 4;
		$i = 0;

		foreach ($collection as $_product) :
			$_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());

	?>

	    <?php if ($i++%$_columnCount==0): ?>
	    
	    <?php endif ?>
	        <div class="featureBox">
                    <div style="height:210px;">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" width="153" height="187" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    </div>
                    <div style="float:left; width:150px; padding-left:5px;">
                    <p>Code:<?php echo $_helper->productAttribute($_product, $_product->getSku()) ?></p>
	            <p><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></p>
	            </div>
                        <?php if($_product->getRatingSummary()): ?>
	            <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
	            <?php endif; ?>
	            <?php echo $this->getPriceHtml($_product, true) ?>
	            <div style="float:left;">
                        <a onclick="setLocation('<?php echo $catalog->getAddToCartUrl($_product) ?>')"><img src="<?php echo $this->getSkinUrl()?>images/cartImg.jpg"></a>
	                <?php if($_product->isSaleable()): ?>
	                    <!--<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $catalog->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>-->
	                <?php else: ?>
	                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	                <?php endif; ?>
	                <ul class="add-to-links">
	                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
	                       <!-- <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>-->
	                    <?php endif; ?>
	                    <?php if($_compareUrl=$catalog->getAddToCompareUrl($_product)): ?>
	                        <!--<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>-->
	                    <?php endif; ?>
	                </ul>
                            
	            </div>
                </div>
	    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
	   
	    <?php endif ?>

		<?php endforeach ?>

        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

	</div>

	<?php endif ?>

